### PR TITLE
Allow comments it .jshintrc. 

### PR DESCRIPTION
**Pull request by chinmaybijwe**
This commit will strip comments from .jshintrc to ensure we have valid json.

### CODE REVIEW

**Comment by chinmaybijwe** [comment]
Thanks for the direction. I'll be back :)

Chinmay

**Comment by huntc** [comment]
Here's one for inspiration: https://github.com/webjars/console-browserify

**Comment by chinmaybijwe** [comment]
Thanks Chris. I'm on it. Submitting to webjars.org

Chinmay

**Comment by chinmaybijwe** [comment]
Hey Chris,
Looks like I didn't add the maven-antrun-plugin in my pom.xml. We might have to create the webjar again :( .
Sorry about the mess up! I realized that after seeing the webjar wasn't producing package.json and strip-json-comments in the target/classes/META-INF/resources/webjars/ folder. I was misled after I saw a zip file containing all that I need. 

Total noob mistake, but I have a much better understanding now. :)

The files that I'm exposing are:
package.json            strip-json-comments.js
which is inline with your example and a couple others I checked. 
 
I have to thank you again for your guidance and involving me in this project. I have a couple of other ideas for this project as well, which we can discuss once we're done with this one :)

**Comment by huntc** [comment]
Hey no worries. I appreciate the attempts. Please raise a PR on the WebJar at the webjar org. Thanks!

**Comment by chinmaybijwe** [comment]
Hey Chris, you think this PR is good to merge? Maybe I throw in another test?

**Comment by huntc** [comment]
One final hurdle: :-)

Would you mind signing our CLA?

http://www.typesafe.com/contribute/cla

Thanks!

**Comment by chinmaybijwe** [comment]
I'm getting this done. Thanks :)

Chinmay

**Comment by chinmaybijwe** [comment]
So I have the corporate CLA signed. Looks like I don't need to send Typesafe this. I just authorized Typesafe with my github account. That should be it right? :)

**Comment by huntc** [comment]
Thanks!

**Pull request merged**
