### PR TITLE
Newer version of sbt-js-engine

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by nafg** [comment]
@benmccann who's responsible for this repository? It's ridiculous that this is sitting here.

**Comment by huntc** [comment]
@benmccann Are you able to release?

**Comment by benmccann** [comment]
@huntc nope. i can't release

**Comment by huntc** [comment]
I shall release and update a few other things.

**Comment by huntc** [comment]
1.0.4 is now released.

**Pull request merged**
